### PR TITLE
Feature/port to arm.

### PR DESCRIPTION
**Pull request by fabianbl**
* New cmake script for detection of the available SIMD instruction sets.
* Changed from `__ARM_NEON__` (works only for armv7) preprocessor directive to `__ARM_NEON` (works for both armv7 and armv8).
* Only part of the library is built on an ARM processor (remaining part is only implemented using SSE SIMD instruction set).

### CODE REVIEW

**Comment by mfehr** [comment]
ok to test

**Comment by mfehr** [comment]
add to whitelist

**Comment by mfehr** [comment]
ok to test

**Comment by mfehr** [comment]
add to whitelist

**Comment by fabianbl** [comment]
test this please

**Comment by fabianbl** [comment]
test this please

**Comment by fabianbl** [comment]
The build job failed because glog_catkin depends on gflags_catkin (which was not cloned by Jenkins).

**Pull request merged**
